name: Static Analysis

on: [push, pull_request, workflow_dispatch]

jobs:
  analysis:

    runs-on: ubuntu-latest

    steps:
    - uses: "actions/checkout@v2"

    - name: "Setup PHP Action"
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: "8.0"
        extensions: "sockets"

    - name: "Install dependencies with Composer"
      uses: "ramsey/composer-install@v2"
      with:
        composer-options: "--prefer-dist --no-progress --no-suggest"

    - name: "PHPStan"
      run: vendor/bin/phpstan analyse
